### PR TITLE
KL - FEATURE: Admin should be able to select driver from dropdown for assigning ride request

### LINKED ISSUE #14: FEATURE: Admin should be able to select driver from dropdown for assigning ride request
### As a...

admin

### I can...

assign drivers to ride requests by selecting from a dropdown

### So that...

I dont have to look up the driver numbers and can select from a list

### Discussion

Right now admins are able to assign drivers to rider's ride requests, but they currently use the ID to shifts.

image

What would be better is a dropdown menu that contains a list of available shifts, with both id and driver name:

```
1 - Andrew Peng
2 - Phill Conrad
```

What would be even better but not a requirement for this feature is either:

* The dropdown shows more information about the shift

```
1 - Andrew Peng - Monday 11:00AM-12:00PM
2 - Phill Conrad - Thursday 01:00PM-3:00PM
```

* OR we only show the shifts that match the day and/or time of the ride request

### Acceptance Criteria

- [ ] When assigning a driver/shift to a ride request, an admin can select from a list of shifts in a dropdown menu as opposed to a text field. This dropdown menu can match any of the solutions presented in the discussion.

### Implementation Todos

Frontend:
- [ ]  Edit `RideAssignDriverForm.js` and instead of a text field for `Shift Id`, there is a dropdown.

Backend:
- [ ] If you decide you want to filter all of the shifts by their day/time you can add a new method to `ShiftController.java`

### PR DESCRIPTION
**Pull request by KarstenLansing**
I added a dropdown list to assign a driver with a shift to a ride in the Admin view of the assigning ride request menu. 
I had to fetch the shift and driver information from the backend, matched them together and mapped them to the dropdown list. 

Acceptance criteria: 
 When assigning a driver/shift to a ride request, an admin can select from a list of shifts in a dropdown menu as opposed to a text field. 

Dokku deployed link: https://gauchoride-karstenlansing-dev.dokku-16.cs.ucsb.edu

Preview 

Screenshot 2024-05-21 at 12 57 53

Screenshot 2024-05-21 at 12 58 06

Closes #14

### CODE REVIEW

**Review by xinyao-song — APPROVED** [review]
LGTM, 
Note the time format for shift and driver availability is HH:MM AM/PM with a space between the time and AM/PM. I am not sure will this cause an issue when things are merged.

**Review by bradygin — APPROVED** [review]
LGTM. The feature works but while reviewing this I did notice discrepancies in validation of times when creating drivers and riders etc. Shouldn't affect this feature, but just wanted to make a note of it.

**Comment by pconrad** [comment]
> LGTM. The feature works but while reviewing this I did notice discrepancies in validation of times when creating drivers and riders etc. Shouldn't affect this feature, but just wanted to make a note of it.

Brady... might be good to create an issue for that.

**Comment by KarstenLansing** [comment]
> LGTM, Note the time format for shift and driver availability is HH:MM AM/PM with a space between the time and AM/PM. I am not sure will this cause an issue when things are merged.

The dropdown list only returns the driver id.

**Comment by KarstenLansing** [comment]
Deployed on dokku

**Review by andrewpengucsb — APPROVED** [review]
LGTM 

Great work

**Pull request merged**
